"""Add file_url to Message

Revision ID: 482ddc928557
Revises: 
Create Date: 2025-06-08 15:51:09.600601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '482ddc928557'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('file_url', sa.String(length=256), nullable=True))
    op.alter_column('message', 'content',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'content',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('message', 'file_url')
    # ### end Alembic commands ###
